### ISSUE TITLE
Add the ability to specify plain text content for io.kestra.plugin.notifications.mail.MailSend

### ISSUE THREAD

**Issue by sceptri** [kestra-io/plugin-notifications#127]
### Feature description

Currently, only the HTML content is specifiable for io.kestra.plugin.notifications.mail.MailSend while the plainTextContent always stays the same, see
https://github.com/kestra-io/plugin-notifications/blob/d8a011b65530bedd9fcf33b30448890b08c3ba4a/src/main/java/io/kestra/plugin/notifications/mail/MailSend.java#L178C46-L178C51

For, e.g. email notifications, it is good to be able to specify plainTextContent - now they always display "Please view this email in a modern email client"

> This seems easy enough, so if it would be prefered I can try to submit a PR myself

**Comment by sceptri** [comment]
Sorry to bother you, @anna-geller :smile: Any thoughts?

**Comment by anna-geller** [comment]
It seems reasonable; definitely feel free to submit a PR 🚀 Contributions are always welcome!

**Comment by hhovhann** [comment]
@anna-geller added initial support and shared in slack contributors channel. 
[Add_plain_text_support#127.patch](https://github.com/user-attachments/files/15524772/Add_plain_text_support.127.patch).

I have no permission to push in future branch and please take a look on patch otherwise please give an access to [my github user](https://github.com/hhovhann)  to push in future branch feat/add-support-for-plain-text-content forked from master branch. 

Thanks

**Comment by anna-geller** [comment]
Usually to contribute, you would need to fork the repository and submit a pull request from the fork to the original repository. Could you do that?

**Comment by hhovhann** [comment]
@anna-geller https://github.com/kestra-io/plugin-notifications/pull/139

**Comment by hhovhann** [comment]
> Usually to contribute, you would need to fork the repository and submit a pull request from the fork to the original repository. Could you do that?

@anna-geller https://github.com/kestra-io/plugin-notifications/pull/139
