### ISSUE TITLE
Raise a friendly error message when SlackExecution is used in a flow without a trigger

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-notifications#98]
### Feature description

When you use any of the execution tasks in a flow without a Flow trigger, it will raise a similar error:

```
Retrying [class ‘net.jodah.failsafe.internal.EventListener’, method ‘lambda$ofAttempt$1’ on line ‘48’], elapsed PT1S and 1 attempts
```

this is because of the polling logic that is expected here.

It would be great to include a nice error message pointing to the equivalent Webhook task e.g. https://kestra.io/plugins/plugin-notifications/tasks/slack/io.kestra.plugin.notifications.slack.slackincomingwebhook for Slack.

**Comment by loicmathieu** [comment]
Same issue as #101, this is because by default the tasks is configured to use the `execution.id` variable whereas inside a trigger you should use `trigger.executionId`.

The default configuration is when used inside a listener so there is a check that the execution is terminated as listeners are executed after the flow completion, this check cannot be passed in this case.
